### ISSUE TITLE
process out of memory Exception 

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xls#77] opened 2015-04-09 05:31 UTC
When xlsjs convert a big excel file(.xls) as readFile(), node get error below

FATAL ERROR: JS Allocation failed - process out of memory 

Can you help me? How to sole it. 

I attempted below setting

$ node --max-old-space-size=8192 my-node-script.js 

If anyone has solution, please response it. : )

**Comment by SheetJSDev** [comment] 2015-04-18 01:54
@JohnJeong123 sorry for belated reply!  Can you give a sense for how large the file is (in MB, as well as row/col)?  If possible, can you share the file?

Also, can you check whether you encounter the allocation problem with the `cfb` utility (want to see where the issue is happening):

```
$ npm install -g cfb
$ cfb -q your_file.xls; echo $?
```

What this does is try to reassemble the file and exit (rather than perform the xls processing)

Again, sorry for such a slow response.

**Comment by starhawkhkk** [comment] 2015-06-29 10:10
```
FATAL ERROR: JS Allocation failed - process out of memory
fish: Job 1, 'cfb -q asdf.xls' terminated by signal SIGABRT (Abort)
```

when running

```
cfb -q asdf.xls
```

**Comment by reviewher** [comment] 2017-03-11 02:54
@JohnJeong123 @githistory we have merged this project into [js-xlsx](https://github.com/SheetJS/js-xlsx).  It replicates the full js-xls API -- please test against the latest version there and if you are still seeing problems please raise an issue there with a sample file.

**Closed by reviewher** 2017-03-11 02:54 UTC
